# Generated by Django 5.1.15 on 2026-06-07 02:08

import django.db.models.deletion
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(help_text='ID legible: bingo-2026, rifa, etc.', max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, help_text='NULL para eventos permanentes/campañas', null=True)),
                ('hora', models.CharField(blank=True, max_length=20, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_bono', models.DecimalField(decimal_places=2, help_text='Precio del bono/boleta en COP', max_digits=10)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, help_text='NULL = sin límite de cupo', null=True)),
                ('cupo_disponible', models.PositiveIntegerField(blank=True, null=True)),
                ('numeracion_min', models.PositiveIntegerField(default=1, help_text='Número mínimo de boleta')),
                ('numeracion_max', models.PositiveIntegerField(default=1000, help_text='Número máximo de boleta')),
                ('permite_seleccion_numero', models.BooleanField(default=True, help_text='Si el usuario puede elegir su número de boleta')),
                ('categoria', models.CharField(choices=[('evento', 'Evento (Bingo, Cena, etc)'), ('campania', 'Campaña Permanente')], default='evento', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ticket', models.PositiveIntegerField(help_text='Número del cartón/boleta — único por evento')),
                ('comprador_nombre', models.CharField(max_length=200)),
                ('comprador_email', models.EmailField(max_length=254)),
                ('comprador_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_verificacion', models.CharField(default=events.models.generate_verification_code, max_length=20, unique=True)),
                ('codigo_qr', models.TextField(blank=True, help_text='Contenido del QR o URL', null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('referencia_wompi', models.CharField(blank=True, max_length=200, null=True)),
                ('donacion_id', models.UUIDField(blank=True, help_text='Referencia a la donación/pago', null=True)),
                ('ticket_enviado', models.BooleanField(default=False)),
                ('seleccion_tipo', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual (Elegido por usuario)')], default='automatico', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'verbose_name': 'Boleta/Ticket',
                'verbose_name_plural': 'Boletas/Tickets',
                'unique_together': {('evento', 'numero_ticket')},
            },
        ),
    ]
