# Generated by Django 5.2.16 on 2026-09-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen promocional del evento. Se redimensiona automáticamente.",
                null=True,
                upload_to="eventos/%Y/%m/",
                verbose_name="Imagen (subir archivo)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="imagen_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Imagen (URL externa)",
            ),
        ),
    ]
