# Generated by Django 5.2.16 on 2026-09-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_imagen_alter_event_imagen_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen promocional del evento. Se optimiza y genera variantes WebP automáticamente.",
                null=True,
                upload_to="eventos/%Y/%m/",
                verbose_name="Imagen (subir archivo)",
            ),
        ),
    ]
