# Generated by Django 5.2.17 on 2026-09-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ticket_comprador_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
