# Generated by Django 5.2.17 on 2026-09-07 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_actualizado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
    ]
