# Generated by Django 5.2.17 on 2026-09-07 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket_creado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checkin_en',
            field=models.DateTimeField(blank=True, help_text='Momento en que se registró la entrada al evento (check-in en puerta).', null=True, verbose_name='Entrada registrada'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checkin_por',
            field=models.ForeignKey(blank=True, help_text='Miembro del personal que registró la entrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Entrada registrada por'),
        ),
    ]
