"""
Django settings for FUNCREES Colombia.

Generated by 'django-admin startproject' using Django 5.1.15.
"""

import os
import sys
import environ
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================
# ENVIRONMENT VARIABLES (via .env)
# ============================================
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    DEFAULT_FROM_EMAIL=(str, 'contacto@funcreescolombia.org'),
    FRONTEND_URL=(str, 'http://localhost:5500'),
    WOMPI_ENV=(str, 'sandbox'),
    EMAIL_HOST=(str, 'smtp.gmail.com'),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# --- SECURITY ---
SECRET_KEY = env('SECRET_KEY', default=None)
if not SECRET_KEY:
    if 'migrate' in sys.argv or 'runserver' in sys.argv:
        # Generar una clave temporal para desarrollo local
        SECRET_KEY = get_random_secret_key()
        print(f"⚠️  ADVERTENCIA: No se encontró SECRET_KEY en .env. Se generó una temporal: {SECRET_KEY}")
    else:
        raise RuntimeError(
            "SECRET_KEY no está definida. Crea un archivo .env basado en .env.example "
            "y define la variable SECRET_KEY."
        )

DEBUG = env('DEBUG')

# En DEBUG mode, permitir localhost automáticamente
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
else:
    ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# ============================================
# APPLICATION DEFINITION
# ============================================

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'django_filters',
    'corsheaders',

    # Local apps
    'beneficiaries',
    'donations',
    'events',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ============================================
# DATABASE
# ============================================

DATABASES = {
    'default': env.db('DATABASE_URL')
}

# ============================================
# CORS & SECURITY
# ============================================

# En DEBUG=True se permiten todos los orígenes (desarrollo local)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000', 'http://localhost:5500', 'http://127.0.0.1:5500', 'http://localhost:3000']
    CORS_ALLOWED_ORIGINS = []
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
    CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')

CORS_ALLOW_CREDENTIALS = True

# Seguridad HTTP (solo en producción con HTTPS)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================
# PASSWORD VALIDATION
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================
# INTERNATIONALIZATION
# ============================================

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ============================================
# STATIC FILES (WhiteNoise)
# ============================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR.parent / 'assets',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============================================
# ADMIN THEME (django-unfold)
# ============================================

UNFOLD = {
    "SITE_TITLE": "Funcrees Admin",
    "SITE_HEADER": "Funcrees Colombia",
    "SITE_URL": "/",
    "SITE_LOGO": {
        "light": lambda request: "/static/Logo.png",
        "dark": lambda request: "/static/Logo.png",
    },
    "COLORS": {
        "primary": {
            "50": "236 253 245", "100": "209 250 229", "200": "167 243 208",
            "300": "110 231 183", "400": "52 211 153", "500": "16 185 129",
            "600": "5 150 105", "700": "4 120 87", "800": "6 95 70",
            "900": "6 78 59", "950": "2 44 34",
        },
    },
}

# ============================================
# DEFAULT PRIMARY KEY
# ============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# DJANGO REST FRAMEWORK
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'donate': '10/hour',
        'contact': '5/hour',
    }
}

# ============================================
# EMAIL CONFIGURATION
# ============================================

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('EMAIL_HOST')
    EMAIL_PORT = env.int('EMAIL_PORT')
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')

# ============================================
# FRONTEND URL (para redirecciones y emails)
# ============================================

FRONTEND_URL = env('FRONTEND_URL')

# ============================================
# WOMPI (Pasarela de Pagos)
# ============================================

WOMPI_ENV = env('WOMPI_ENV')
WOMPI_PUBLIC_KEY = env('WOMPI_PUBLIC_KEY')
WOMPI_PRIVATE_KEY = env('WOMPI_PRIVATE_KEY')
WOMPI_INTEGRITY_SECRET = env('WOMPI_INTEGRITY_SECRET')

# ============================================
# ENCRYPTION KEY (Fernet — Ley 1581 Habeas Data)
# ============================================

ENCRYPTION_KEY = env('ENCRYPTION_KEY', default=None)
if not DEBUG and not ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        "ENCRYPTION_KEY no está definida en producción. "
        "Genera una con: python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'"
    )
if not ENCRYPTION_KEY:
    # Solo para desarrollo local sin esta clave definida
    from cryptography.fernet import Fernet
    ENCRYPTION_KEY = Fernet.generate_key().decode()
    print("⚠️  ADVERTENCIA: ENCRYPTION_KEY temporal generada. Define una fija en .env para desarrollo.")

# ============================================
# LOGGING
# ============================================

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'donations': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
