# Generated by Django 5.2.16 on 2026-09-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto del beneficiario. Formatos: JPG, PNG. Se redimensiona automáticamente.",
                null=True,
                upload_to="beneficiarios/%Y/%m/",
                verbose_name="Foto (subir archivo)",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="foto_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Foto (URL externa)"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="video_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Video (URL, ej. YouTube)",
            ),
        ),
    ]
