# Generated by Django 5.2.16 on 2026-09-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0002_beneficiary_foto_alter_beneficiary_foto_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto del beneficiario. Formatos: JPG, PNG. Se optimiza y genera variantes WebP automáticamente.",
                null=True,
                upload_to="beneficiarios/%Y/%m/",
                verbose_name="Foto (subir archivo)",
            ),
        ),
    ]
