# Generated by Django 5.2.17 on 2026-09-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta General'), ('apadrinamiento', 'Apadrinamiento de Adulto Mayor'), ('alianza', 'Alianza Corporativa'), ('voluntariado', 'Voluntariado'), ('eventos', 'Eventos y Bonos Solidarios'), ('donacion', 'Donación'), ('otro', 'Otro')], default='consulta', max_length=20),
        ),
    ]
