# Generated by Django 5.1.15 on 2026-06-07 02:08

import django.db.models.deletion
import donations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('general', 'Donación General'), ('apadrinamiento', 'Apadrinamiento Mensual'), ('patrocinio', 'Patrocinio Empresarial'), ('boleta', 'Compra de Boleta/Evento')], default='general', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donante_nombre', models.CharField(max_length=200)),
                ('donante_email', models.EmailField(max_length=254)),
                ('donante_documento_cifrado', donations.models.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Documento (Cifrado)')),
                ('donante_telefono_cifrado', donations.models.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Teléfono (Cifrado)')),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('referencia_pasarela', models.CharField(blank=True, max_length=200, null=True)),
                ('wompi_response', models.JSONField(blank=True, null=True)),
                ('certificado_enviado', models.BooleanField(default=False)),
                ('autorizacion_datos', models.BooleanField(default=False)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donante_nombre', models.CharField(max_length=200)),
                ('donante_email', models.EmailField(max_length=254)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('debito_automatico', 'Débito Automático'), ('suscripcion_manual', 'Suscripción Manual')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='activo', max_length=20)),
                ('wompi_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('wompi_token_card', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_proximo_cobro', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_cobro', models.DateTimeField(blank=True, null=True)),
                ('ciclos_completados', models.PositiveIntegerField(default=0)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apadrinamientos', to='beneficiaries.beneficiary')),
            ],
            options={
                'verbose_name': 'Apadrinamiento',
                'verbose_name_plural': 'Apadrinamientos',
            },
        ),
    ]
