# Generated by Django 6.0.6 on 2026-06-19 03:38

import donations.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='wompi_token_card',
            field=donations.models.EncryptedCharField(blank=True, max_length=1000, null=True, verbose_name='Token Tarjeta (Cifrado)'),
        ),
    ]
