# Generated by Django 6.0.6 on 2026-06-19 03:38
# Convertida en migración de datos: cifra los tokens de tarjeta existentes
# (almacenados como plaintext en el TextField original) ANTES de cambiar el
# tipo de campo a EncryptedCharField.

import logging
import donations.models
from django.db import migrations, connection

logger = logging.getLogger(__name__)


def forward(apps, schema_editor):
    """
    Migra los tokens de tarjeta existentes a su forma cifrada (Fernet).

    Antes de esta migración, `wompi_token_card` era un TextField plano (sin
    cifrar). Esta función debe ejecutarse ANTES de AlterField para que los
    datos existentes no queden como plaintext una vez que el campo se vuelva
    EncryptedCharField (que asumiría que ya están cifrados al leerlos y, al
    fallar el descifrado, devolvería None).

    Usa SQL crudo (connection.cursor()) para evitar que el ORM aplique
    auto-cifrado/descifrado durante el proceso. Cada fila se examina:
    - Si el valor desencripta correctamente con Fernet, ya estaba cifrado
      (idempotente) y se omite.
    - Si falla el descifrado, se asume plaintext y se cifra.
    """
    from donations.models import get_fernet
    from cryptography.fernet import InvalidToken

    fernet = get_fernet()

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, wompi_token_card FROM donations_sponsorship "
            "WHERE wompi_token_card IS NOT NULL AND wompi_token_card != ''"
        )
        rows = cursor.fetchall()

    updated = 0
    skipped = 0
    for row_id, token in rows:
        if not token:
            continue

        # Detectar si ya está cifrado: intentar desencriptar.
        try:
            fernet.decrypt(token.encode('utf-8'))
            # Desencriptó correctamente -> ya estaba cifrado. Skip.
            skipped += 1
            continue
        except (InvalidToken, Exception):
            # No es un token Fernet válido -> está en plaintext -> cifrar.
            pass

        encrypted = fernet.encrypt(token.encode('utf-8')).decode('utf-8')
        # SQL crudo: evita que get_prep_value() vuelva a cifrar el valor.
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE donations_sponsorship "
                "SET wompi_token_card = %s WHERE id = %s",
                [encrypted, row_id],
            )
        updated += 1

    logger.info(
        "[migración donations/0002] tokens cifrados: %d, ya estaban cifrados: %d",
        updated, skipped,
    )


def reverse(apps, schema_editor):
    """
    Reverso intencionalmente NO desencripta los tokens por seguridad:
    dejar tokens en plaintext sería un retroceso de seguridad. El campo
    vuelve a TextField pero el contenido queda opaco (cifrado). Si se
    necesita leerlos, re-ejecutar `forward` desde una versión anterior.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        # 1) Migrar datos existentes (plaintext -> cifrado) ANTES de cambiar
        #    el tipo de campo. El campo aún es TextField, así que el ORM no
        #    interfiere con el cifrado.
        migrations.RunPython(forward, reverse_code=reverse),
        # 2) Cambiar el tipo de campo a EncryptedCharField.
        migrations.AlterField(
            model_name='sponsorship',
            name='wompi_token_card',
            field=donations.models.EncryptedCharField(blank=True, max_length=1000, null=True, verbose_name='Token Tarjeta (Cifrado)'),
        ),
    ]
