# Generated by Django 5.2.17 on 2026-09-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_encrypt_wompi_token_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='revision_requerida',
            field=models.BooleanField(default=False, verbose_name='Revisión requerida'),
        ),
    ]
